### ISSUE TITLE
What is window.byted_acrawler.sign?

### ISSUE THREAD

**Issue by sethamus** [carcabot/tiktok-signature#70]
I am trying to use this to scrape data from a video link, like username, like count etc. However this seems to require a signature now. Since I am using this with the Dart language I can’t for the love god find out what is window.byted_acrawler.sign so I can generate a signature. What is it?

**Comment by tokjii** [comment]
`byted_acrawler.sign` takes parameters such as `window.tac`, your browser's user agent and the target link that you want to get data from and calculates a signature based on that.

Theoretically you should be able to inspect element and then reverse engineer what the function actually does and reimplement this very functionality in Dart but, without being able to remember how big this function actually was, I'd advice against that. Especially since it can change every other week.

What I recommend you to do is to write your whole application in Dart but ship with a Selenium build that gets the signatures for you so you can make use of this repo's JS code and then use the signature in Dart.
